### ISSUE TITLE
Bug/Unexpected effect in global timestamp computation

### ISSUE THREAD

**Issue by larsrollik** [open-ephys/open-ephys-python-tools#21]
OpenEphys GUI: `0.6.4`
open-ephys-python-tools: `0.1.4`

In a recently acquired session, global timestamps are miscalculated, because the events are sorted by `timestamp`, but the `sample_number` is therefore shuffled. When the global timestamp function takes the `iloc[0]` and `iloc[-1]` `sample_number`, then these are **not** the first and last sample in the acquisition.

You can see already in the head of the events dataframe that the sorting of the `sample_number` is random:

```
Out[1]: 
       line  sample_number    timestamp  ...  stream_index  stream_name state
0         1      113210450 -9906.177509  ...             1    ProbeA-AP     1
1         1      113209520 -9840.472230  ...             1    ProbeA-AP     0
2         1      113208648 -9778.864699  ...             1    ProbeA-AP     1
3         1      113206516 -9628.237112  ...             1    ProbeA-AP     0
4         1      113206244 -9609.020084  ...             1    ProbeA-AP     1
...     ...            ...          ...  ...           ...          ...   ...
25263     1       12873859   149.820794  ...             0   ProbeA-LFP     0
25264     1       12874087   149.911938  ...             0   ProbeA-LFP     1
25265     1       12510866   149.958667  ...             0   ProbeA-LFP     1
25266     1       12510889   149.967867  ...             0   ProbeA-LFP     0
25267     1       12510992   150.009067  ...             0   ProbeA-LFP     1
```

When checking the synchronization event counts and sample differences between the synch channels, they match perfectly, just not according to the built-in function.

Note that with the negative `timestamp` values, the timestamps set to `-1` as `not synchronized` are in the middle section of the events dataframe.

**Comment by medengineer** [comment]
Hi, 

This should be fixed in the latest release here: 

https://pypi.org/project/open-ephys-python-tools/0.1.5/

**Comment by larsrollik** [comment]
Sorry, I misread in the diff of the latest merge that the sorting of the events dataframe was changed, but this is not the case for BinaryRecording instances.

See https://github.com/open-ephys/open-ephys-python-tools/blob/e7a665693aeea80aa91c702cd55a986b48640b7f/src/open_ephys/analysis/formats/BinaryRecording.py#L206-L209.

The original issue remains in https://github.com/open-ephys/open-ephys-python-tools/releases/tag/v0.1.5

**Comment by medengineer** [comment]
I see. Does changing _timestamp_ to _sample_number_ on line 207 above fix the issue on your end w/ version 0.1.5?
